# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0002_auto_20160824_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='blog_posts',
        ),
    ]
