# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0005_auto_20160907_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English')], max_length=64, null=True, verbose_name='language'),
        ),
    ]
