# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0006_event_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_event',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'French'), ('en', 'English')], max_length=64, null=True, verbose_name='Language'),
        ),
    ]
