# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0007_auto_20160923_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='featured_name',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='room',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='room'),
        ),
    ]
