# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0008_auto_20160926_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_text',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Date text'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='room',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Date text'),
        ),
    ]
