# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0009_auto_20160927_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
    ]
