# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0010_remove_event_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mentions',
            field=models.TextField(blank=True, verbose_name='mentions'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='room',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='room'),
        ),
    ]
