# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0011_auto_20161005_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_title_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='event',
            name='sub_title_fr',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='sub title'),
        ),
    ]
