# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0013_auto_20161010_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='no_price_comments',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='No price comments'),
        ),
        migrations.AddField(
            model_name='event',
            name='no_price_comments_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='No price comments'),
        ),
        migrations.AddField(
            model_name='event',
            name='no_price_comments_fr',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='No price comments'),
        ),
    ]
