# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-04-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0018_event_is_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False, verbose_name='Is Full'),
        ),
    ]
