# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-25 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0019_auto_20170415_0948'),
        ('mezzanine_agenda', '0021_auto_20170626_1817'),
    ]

    operations = [
    ]
