# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-07-26 14:05
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mezzanine_agenda', '0024_auto_20170725_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='no_price_comments',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='No price comments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_price_comments_en',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='No price comments'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_price_comments_fr',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='No price comments'),
        ),
    ]
